name: "ETH Cyrograf: linter analysis"

on:
  pull_request:
    branches: [ master ]
    paths: [ 'eth/**' ]

jobs:
  analyze:
    runs-on: ubuntu-latest
    name: ETH Lint
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Linter analysis with Slither
      uses: crytic/slither-action@v0.4.0
      id: slither
      with:
        target: 'eth/'
