name: Deploy proxied ETH contract to testnet

# on:
#   workflow_dispatch: {}
#   pull_request:
#     branches: [ master ]
#     paths: [ 'eth/**' ]
#     types: [ closed ]

jobs:
  deploy-testnet:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Upgrade contract to a new implementation
        uses: piotrjwegrzyn/evm-deployment@v2.1.0
        id: upgrade-testnet
        with:
          implementation-contract-name: 'Cyrograf'
          proxy-contract-address: ${{ steps.deploy.outputs.proxy-contract-address }}
          parent-dir: 'eth/'
          deployer-pk: ${{ secrets.DEPLOYER_PK }}
          chain-id: '11155111'
          rpc-url: ${{ secrets.RPC_ETH_SEPOLIA_HTTPS }}
          verify: true
          etherscan-url: 'https://sepolia.etherscan.io'
          etherscan-api-key: ${{ secrets.ETHERSCAN_SEPOLIA_API_KEY }}
