name: "UI Cyrograf: validator"

on:
  pull_request:
    branches: [ master ]
    paths: [ 'ui/**' ]

jobs:
  validate:
    runs-on: ubuntu-latest
    name: UI Validate
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: HTML5Validator
      uses: Cyb3r-Jak3/html5validator-action@v7.2.0
      with:
        root: ui/
        blacklist: sc_connector.json